#!/bin/bash
echo "=== ПРОВЕРКА ИСПРАВЛЕНИЙ ==="
echo ""
echo "1. Фиолетовые цвета:"
grep -r "Color\.PURPLE\|Color\.MAGENTA" src/main/java/uwu/openjfx/ 2>/dev/null || echo "   ✅ НЕТ фиолетовых цветов"
echo ""
echo "2. Неправильные пути:"
grep -r "\.\/weapons\/" src/main/java/uwu/openjfx/ 2>/dev/null || echo "   ✅ НЕТ неправильных путей"
echo ""
echo "3. JAR файл:"
ls -lh build/libs/royal-demons.jar 2>/dev/null && echo "   ✅ JAR существует"
echo ""
echo "4. Отчеты созданы:"
ls -1 *.md | grep -E "(PURPLE|MAGIC)" && echo "   ✅ Отчеты созданы"
